### PR TITLE
Add advice for apply autotags now

### PR DESCRIPTION
**Pull request by fasheng**
Make entry title matching rules works with the new added `elfeed-apply-autotags-now` in elfeed :)

### CODE REVIEW

**Comment by remyhonig** [comment]
apologies for the late response, when I find the time to test the code I'll merge it but it could take a while, sorry.

**Comment by Thaodan** [comment]
Still interested in this?

**Comment by remyhonig** [comment]
Oh my, 6 years already, haha. Well I'd be happy to merge it but it has conflicts. If you'd like to have it, it would help me out if you could provide a PR with the conflicts solved.

**Comment by Thaodan** [comment]
Yeah it has been a while :D

I might be still handy, I can resolve the conflict.

However @fasheng might no better if it still needed since there's this
suggestion:

To make elfeed-org tag rules works together with elfeed-protocol, just add a after advice for elfeed:
```
(defadvice elfeed (after configure-elfeed-feeds activate)
  "Make elfeed-org autotags rules works with elfeed-protocol."
  (setq elfeed-protocol-tags elfeed-feeds)
  (setq elfeed-feeds (list
                      (list ***@***.***"
                            :password '(password-store-get "owncloud/app-pass")
                            :autotags elfeed-protocol-tags))))
```


https://github.com/fasheng/elfeed-protocol#initialization

However I might mix things up.

**Comment by fasheng** [comment]
Really old PR for me :)

@Thaodan  Glade to see you resolve the conflict, and test the PR is easy:
1. keep entries existed in elfeed
2. change elfeed-org title matching rules for the existed entries
3. run `elfeed-apply-autotags-now` with this PR, then the existed entries' tags will update, too.

And the example code in elfeed-protocol's initialization section is only work for `elfeed-protocol`, it have nothing to do with this PR. Just ignore it.

**Comment by Thaodan** [comment]
Hey, I rebased the PR now.
I missread the docs from elfeed-autotag, I assumed that elfeed-autotag depends on this package
as it uses org-mode.

The PR should work just fine still I think. However I didn't test it has I don't have feeds besides
those from elfeed protocol.

However I think it might make sense to merge elfeed-autotag as both apply takes based on rules of
an org file.

**Pull request closed without merging**
