### PR TITLE
Support ignore invalid feeds automatically

### PR DESCRIPTION
**Pull request by fasheng**
Sometimes mark the invalid feeds with special tag and ignore them is necessary.

### CODE REVIEW

**Comment by remyhonig** [comment]
Thank you for your nice PR! I love that you added tests! I submitted a PR to `elfeed` back in 2015 to make hooks for the error events in https://github.com/skeeto/elfeed/pull/70 but I never did the work to handle those events in `elfeed-org`. It was a feature I thought would be really cool and you made it possible now. Thank you very much!

May I ask you a favor? I would love to have a test for the `rmh-elfeed-org-handle-http-error` function before I merge this into master because it will make edits to the users org files. If you don't have the time I'll do it, but I haven't programmed in elisp for a while so I'll have to setup my development environment and get used to programming in elisp again. Could you let me know if you are willing to? 

Thanks again!

**Comment by fasheng** [comment]
Sure, I will do it soon..

**Comment by fasheng** [comment]
Thanks for your notice, the test case really could improve my code, I fixed a bug just now XD.

Now I split the function and add hook to `elfeed-parse-error-hooks` for some case the feed could access but maybe just a notice out-of-date page.

**Comment by fasheng** [comment]
Now it's `(void-function string-suffix-p)` error for emacs24.3, looks we should use another one instead...

**Pull request merged**
