### PR TITLE
Add support for abbreviated links

### LINKED ISSUE #58: Feature request: Support link abbreviation
It would be nice to support org-mode's [link abbreviation](https://orgmode.org/manual/Link-Abbreviations.html#Link-Abbreviations).

Here is a simple example:
``` org
#+link: foo https://example.com/

* [[Bar][foo:bar]]
This headline link to https://example.com/bar.
```

### PR DESCRIPTION
**Pull request by bricewge**
Fix #58.

It doesn't seem clean to me but at least it works.

I don't care if it isn't merged in this form.

### CODE REVIEW

**Comment by bricewge** [comment]
@remyhonig could you review this PR please?

**Comment by remyhonig** [comment]
Thanks for your PR! I will merge it regardless, but could I just ask you for one favor? I would really appreciate it if you could incorporate an example in the documentation so people know why and how to use it. 

----- 
image

**Comment by bricewge** [comment]
I've added an example to the README without mentioning the "feature" since it's more of a fix since this is a standard org-mode link syntax.

I've been using this PR daily for months, but the initial version failed on some tests; poor quality control on my part. Current PR don't fail on tests but my code is ugly. Let me time to refactor it.

**Comment by bricewge** [comment]
This version should be good enough. WDYT?

**Comment by remyhonig** [comment]
Well, let's say better late then never. Thank you for your patience.

**Pull request merged**
